#!/usr/bin/env python3
"""Build tools/gen-art/preview.html: dark page rendering both FMT1 art files
as CSS grids of half-block cells (fg = top half, bg = bottom half)."""

import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))


def parse(path):
    with open(path, encoding="utf-8") as f:
        lines = [ln.rstrip("\n") for ln in f if ln.strip()]
    cols, rows = map(int, lines[0].split()[1].split("x"))
    grid = []
    for ln in lines[1:]:
        row = []
        for t in ln.split(" "):
            fg, bg = t[1:].split("/")
            row.append((fg, bg))
        grid.append(row)
    return cols, rows, grid


def render_art(path, cell_w, cell_h):
    cols, rows, grid = parse(path)
    cells = []
    for row in grid:
        for fg, bg in row:
            cells.append(
                '<i style="background:linear-gradient(180deg,%s 50%%,%s 50%%)">'
                "</i>" % (fg, bg)
            )
    return (
        '<div class="art" style="grid-template-columns:repeat(%d,%dpx);'
        'grid-auto-rows:%dpx">%s</div>'
        % (cols, cell_w, cell_h, "".join(cells))
    ), cols, rows


def main():
    main_html, mc, mr = render_art(
        os.path.join(ROOT, "assets", "eye-art-96.txt"), 10, 20)
    side_html, sc, sr = render_art(
        os.path.join(ROOT, "assets", "eye-art-side.txt"), 20, 40)
    html = """<!DOCTYPE html>
<html lang="pt-BR">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>eye-art preview (FMT1 half-block truecolor)</title>
<style>
  :root { color-scheme: dark; }
  body {
    margin: 0; padding: 32px; background: #0b0710; color: #e8d5ee;
    font: 14px/1.5 "Cascadia Code", Consolas, monospace;
  }
  h1 { font-size: 18px; color: #ff3ea5; letter-spacing: 1px; }
  h2 { font-size: 13px; color: #ffc43c; margin: 28px 0 8px; }
  .art {
    display: grid; width: max-content;
    outline: 1px solid #2a1533;
    box-shadow: 0 0 40px #ff3ea522, 0 0 120px #7b2cbf22;
    image-rendering: pixelated;
  }
  .art i { display: block; }
  .note { color: #9a7fae; font-size: 12px; margin: 6px 0 0; }
</style>
</head>
<body>
<h1>&#9612; eye-art &mdash; FMT1 half-block truecolor preview</h1>
<p class="note">Each terminal cell renders <code>&#9612;</code> with fg = top pixel half, bg = bottom pixel half.</p>

<h2>assets/eye-art-96.txt &mdash; %dx%d cells (window art)</h2>
%s

<h2>assets/eye-art-side.txt &mdash; %dx%d cells (sidebar art, eye crop)</h2>
%s

<p class="note">Generated by tools/gen-art/gen.py &middot; render check: tools/gen-art/preview.py</p>
</body>
</html>
""" % (mc, mr, main_html, sc, sr, side_html)
    out = os.path.join(HERE, "preview.html")
    with open(out, "w", encoding="utf-8") as f:
        f.write(html)
    print("wrote %s (%.1f KB)" % (out, len(html) / 1024.0))


if __name__ == "__main__":
    main()
